#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = /usr/bin/dbus-update-activation-environment --all
exec-once = /usr/libexec/hyprpolkitagent
exec-once = ~/.config/hypr/scripts/startXDG.sh
exec-once = gnome-keyring-daemon --start --components=pkcs11,secrets,ssh
exec-once = hypridle

exec-once = pipewire
exec = killall mako; mako
exec-once = killall wl-clip-persist; wl-clip-persist --clipboard regular

exec-once = nm-applet --indicator
exec-once = blueman-applet
exec-once = copyq --start-server

# finalize
exec-once = hyprpaper
#exec = killall linux-wallpaperengine; sleep 1; ~/Source/linux-wallpaperengine/build/output/linux-wallpaperengine --assets-dir ~/Source/linux-wallpaperengine/build/output/assets ~/Source/Wallpaper/extracted --fps 24 --screen-root eDP-1 --silent
exec = killall waybar; waybar

exec-once = ~/.config/hypr/scripts/brightnessctl.sh restore
exec-once = keyd-application-mapper -d

# now start userapps
exec-once = signal-desktop --start-in-tray
exec-once = easyeffects --gapplication-service
exec-once = xdman -m
