################
### MONITORS ###
################
# See https://wiki.hyprland.org/Configuring/Monitors/

# decrease padding on sides of monitor
# top, bottom, left, right
#monitor=,addreserved, -20, -20 , -20 , -20

monitor = eDP-1, 1920x1080@60.00000, 0x0, 1
monitor = desc:Dell Inc. DELL 1908FP DY84083UH15L, 1280x1024@75.03, 1920x0 ,1
