##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
# https://github.com/hyprwm/Hyprland/raw/refs/heads/main/example/hyprland.conf

# use hyprctl clients to get class names

# Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class .*, suppress_event maximize

# Fix some dragging issues with XWayland
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# hyprland-run windowrule
windowrule = match:class hyprand-run, move 20 monitor_h-120, float true

# try to catch all file system popups
# For Open/Save File/Folder dialogs
windowrule = match:title ^(Open|Save) (File|Folder|As)$, float true
windowrule = match:class (xdg-desktop-portal-gtk), float true

# picture in picture
windowrule = match:title (Picture-in-Picture), float true
windowrule = match:title (Picture-in-Picture), size 640 360, float true

# about
windowrule = match:title ^(About.*)$, float true

# For Enter name of file to save to dialog
windowrule = match:title "Enter name of file to save to…", float true
windowrule = match:title Location for Image File, float true
windowrule = match:title .*wants to save, size 1024 768, float true

# Network Manager
windowrule = match:class nm-connection-editor, match:title (Editing *), float true

# fontforge
windowrule = match:class fontforge, match:title (SymbolsNFM.*), tile true

# Virtman
windowrule = match:title (Virtual Machine Manager), size 800 600, float true

# brasero
windowrule = match:title Creating Image, match:class brasero, float true

# Thunar
windowrule = match:title (File Operation Progress), float true
windowrule = match:title (Rename.*), float true
windowrule = match:title (Extract files), float true

# removes dim in window menus
windowrule = match:title ^$, match:class ^$, dim_around false
windowrule = match:title ^$, match:class ^$, opaque true

windowrule = match:title ^(Calculator)$, float true
windowrule = match:class ^(org.gnome.Calendar), float true

# file selector
windowrule = match:title ^(Open Files)$, float true
windowrule = match:class thunar, match:title Rename.*, float true

# CopyQ
windowrule = match:class (com.github.hluk.copyq), float true

# Celluloid
windowrule = match:class io.github.celluloid_player.Celluloid, float true

# panel
windowrule = match:class (xfce4-panel), float true
windowrule = match:class wrapper-2.0, float true

# steam
windowrule = match:title Steam Settings, float true

# logisim
windowrule = match:class com-cburch-logisim-Main, tile true
windowrule = match:class com-cburch-logisim-Main, match:title ^(Open|Load RAM Image|Logisim: Hex Editor|Confirm Clear)$, float true
windowrule = match:class com-cburch-logisim-Main, match:title (Logisim 2.7.1), float true
windowrule = match:class com-cburch-logisim-Main, match:title (win[0-9]), float true

# MatLab
windowrule = match:class (MATLAB R2025b.*), float false

# MINECRAFT
windowrule = match:class (com.mojang.minecraft), float true

# wvkbd-mobintl
windowrule = match:class (wvkbd), float true

# Virtuoso
windowrule = match:class (Virtuoso|virtuoso), match:title ^(Log:.*), float true
windowrule = match:class (Virtuoso|virtuoso), match:title (Open Cellview Progress), float true

# assetto
windowrule = match:class (steam_app_244210), float true
