timeout 120 '~/.config/sway/scripts/lock.sh set' resume '~/.config/sway/scripts/brightnessctl.sh restore'
timeout 300 '~/.config/sway/scripts/lock.sh lock'
timeout 330 '~/.config/sway/scripts/screenCtrl.sh disable' resume '~/.config/sway/scripts/screenCtrl.sh enable'
timeout 1800 'loginctl suspend'
before-sleep '~/.config/sway/scripts/lock.sh set && ~/.config/sway/scripts/lock.sh lock'
lock '~/.config/sway/scripts/lock.sh --screenshot'
